version: '3.7'

networks:
  backend:
    driver: bridge

services:
  camouflage:
    image: camouflage
    networks:
      - backend
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

  trojan-server:
    image: trojangfw/trojan
    volumes:
      - ./config:/config
    networks:
      - backend
    ports:
      - 443:443
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
